### PR TITLE
update the crate to edition 2018 and update arc-swap to 0.4

### PR DESCRIPTION
**Pull request by koushiro**
Signed-off-by: koushiro <koushiro.cqx@gmail.com>

### CODE REVIEW

**Comment by koushiro** [comment]
@breeswish PTAL

**Comment by koushiro** [comment]
I think it's better to publish a version to crates.io

**Review by breezewish — APPROVED** [review]
Thanks! I'm still not sure about whether this package should be published, considering that it's scenario might be limited. Do you use it in your projects now?

**Comment by koushiro** [comment]
> Thanks! I'm still not sure about whether this package should be published, considering that it's scenario might be limited. Do you use it in your projects now?

No, I don't use it in my own projects. 
Just a suggestion, you can ignore it.

**Comment by breezewish** [comment]
@koushiro Good to know, thanks! I will publish it if some one has demands.

**Pull request merged**
