### PR TITLE
flush async logger when dropping global logger

### LINKED ISSUE #8998: Panic log may be lost when using async logger
### What version of TiKV are you using?

`187774ed9433af80d117b6576179515b2e24ab6a`

### Steps to reproduce

Start a runner on thread pool to panic as https://github.com/zhongzc/tikv/commit/bcda8dca653988169b96d3cb45e254594520019e.

### What did you expect?

The panic log can be guaranteed to see.

### What did happened?

I couldn't get the `boom!` panic output.

### PR DESCRIPTION
**Pull request by zhongzc**
Signed-off-by: zhongzc <zhongzc_arch@outlook.com>

To fix tikv/tikv#8998

### CODE REVIEW

**Comment by zhongzc** [comment]
cc @breeswish

**Comment by breezewish** [comment]
Is it possible to use ArcSwap for the AsyncGuard as well?

**Comment by zhongzc** [comment]
I think my implementation is wrong. We should guarantee the setting of `Logger` and `AsyncGuard` is atomic.

**Comment by zhongzc** [comment]
I tried this patch in tikv. Got following core dump during integration testing

```
pure virtual method called
terminate called without an active exception
```

Maybe I need a thoughtful consideration. Close this PR for now.

**Pull request closed without merging**
